<?php
/**
* @category   Entrepids
* @package    Entrepids_Nestle
* @author     fabian.perez@entrepids.com
* @website    http://www.entrepids.com
*/
?>

<?php 
    $validations = $this->validate;
    $input_name = 'rfc';
    $input_id = $input_name;
    if($this->input_prefix){
        $input_name = $this->input_prefix."[$input_name]";
        $input_id = $this->input_prefix.':'.$input_id;
    }
    
    $label = '<label for="'. $input_id.'">';
    if (strpos($validations, 'required-entry') !== false) {
        $label = '<label for="'. $input_id.'" class="required"><em>*</em>';
    }

    
?>  
<?php echo $label.$this->__('RFC') ?></label>
<div class="input-box">
    <input type="text" autocapitalize="off" autocorrect="off" spellcheck="false" name="<?= $input_name ?>" id="<?= $input_id?>" value="<?php echo $this->escapeHtml($this->rfc) ?>" title="<?php echo $this->quoteEscape($this->__('RFC')) ?>" class="input-text required-entry validate-rfc <?= $validations ?>" />
</div>

<script type="text/javascript">
    //<![CDATA[
        Validation.add('validate-rfc', 'Por favor, ingresa un RFC válido.', function(v,elem) {
            if(elem.hasClassName('required-entry') || v.length){
                return v.match(/^([A-Z|a-z]{3,4}([0-9]{2})((02(0[1-9]|1[0-9]|2[0-9]))|((0[1|3|5|7|8]|1[0|2])(0[1-9]|1[0-9]|2[0-9]|3[0-1]))|((0[4|6|9]|11)(0[1-9]|1[0-9]|2[0-9]|3[0])))[(A-Z|a-z)|\d]{3})$/);
            }
            return true;
        });
    //]]>
</script>