
<?php $_code=$this->getMethodCode(); ?>

<style type="text/css">
.More-Options a {
	color:#00BFEC;
	text-decoration:none;
	font-size:14px;
	cursor:pointer !important;
	padding-bottom:40px;
}
.More-Options a:hover {
	color:#2693ff;
}
</style>
<ul class="form-list checkmo-list" id="payment_form_<?php echo $_code; ?>" style="display:none;">
     <li>
    	Múltiples puntos ubicados a lo largo de todo México
        <div class="More-Options"><a href="http://www.openpay.mx/tiendas-de-conveniencia.html" style="padding: 0px;" target="_blank">Ver red de tiendas afiliadas</a></div>
     </li>
</ul>
