<!doctype html>
<html>
    <head>
        <title>Pago en tienda de conveniencia</title>
        <link href="/favicon.ico?v=5" rel="icon" type="image/x-icon" />
        <link href="/favicon.ico?v=5" rel="shortcut icon" type="image/x-icon" />


        <link href="<?php echo $this->getSkinUrl('css/stores/pago.css');?>" rel="stylesheet" type="text/css">
        <meta charset="UTF-8">
    </head>

    <body>
        <div class="margen">
            <iframe id="pdf" src="<?php echo $this->getPdfUrl() ?>" style="width:100%; height:850px; visibility: visible !important; opacity: 1 !important;" frameborder="0"></iframe>    

            <div class="buttons">        
                <a href="<?php echo $this->getBaseUrl();?>">Sigue comprando</a>
            </div>
        </div>

    </body>
</html>
