
<?php $_code=$this->getMethodCode(); ?>

<style type="text/css">
.More-Options a {
	color:#00BFEC;
	text-decoration:none;
	font-size:14px;
	cursor:pointer !important;
	padding-bottom:40px;
}
.More-Options a:hover {
	color:#2693ff;
}
</style>
<ul class="form-list checkmo-list" id="payment_form_<?php echo $_code; ?>" style="display:none;">
	<li>
		Desde cualquier banco de México con servicio SPEI
		<div class="More-Options"><a href="http://www.openpay.mx/bancos.html" target="_blank" style="padding: 0px;">Ver Bancos con servicio de SPEI</a></div>
    </li>
</ul>

